all:
	@g++ -oBurbuja.bin Burbuja.cpp -std=c++11
	@g++ -oMergeSort.bin mergesort.cpp -std=c++11
	@g++ -o Ejercicio1.bin Ejercicio1.cpp -std=c++11

Ejercicio1:
	@g++ -o Ejercicio1.bin Ejercicio1.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo con ./Ejercicio1.bin 12345 salida.txt
	
clean:
	rm *.bin
