all:
	@g++ -oBurbuja.bin Burbuja.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo iterativo con ./Burbuja.bin salida.txt 12345 1000 2000 3000
	@g++ -oMergeSort.bin mergesort.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./MergeSort.bin salida.txt 12345 1000 2000 3000
	@g++ -oMaximoMinimoDyV.bin MaximoMinimoDyV.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./MaximoMinimoDyV.bin salida.txt 12345 1000 2000 3000
	@g++ -oinsertarEnPos.bin insertarEnPos.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./insertarEnPos.bin salida.txt 12345 1000 2000 3000
	@g++ -oreestructurarRaiz.bin reestructurarRaiz.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./reestructurarRaiz.bin salida.txt 12345 1000 2000 3000	
	@g++ -oHeapSort.bin HeapSort.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo con ./HeapSort.bin salida.txt 12345 1000 2000 3000
	@g++ -oComparativa.bin Comparativa.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo con ./Comparativa.bin salida.txt 12345 1000 2000 3000
